Update tests

diff --git a/7.1/test/tests b/7.1/test/tests
--- a/7.1/test/tests
+++ b/7.1/test/tests
@@ -6,33 +6,29 @@ if [[ -n "${DEBUG}" ]]; then
   set -x
 fi
 
-function checkPhpModules {
-    php -m > ~/php_modules.tmp
-    echo -n "Checking PHP modules... "
+php -m > ~/php_modules.tmp
+echo -n "Checking PHP modules... "
 
-    if ! cmp -s ~/php_modules.tmp ~/php_modules; then
-        echo "Error. PHP modules are not identical."
-        diff ~/php_modules.tmp ~/php_modules
-        exit 1
-    fi
+if ! cmp -s ~/php_modules.tmp ~/php_modules; then
+    echo "Error. PHP modules are not identical."
+    diff ~/php_modules.tmp ~/php_modules
+    exit 1
+fi
 
-    echo "OK. PHP modules are identical"
-}
+echo "OK. PHP modules are identical"
 
-function checkTools {
-    echo -n "Checking composer... "
-    composer --version | grep -q 'Composer version'
-    echo "OK"
-    echo -n "Checking walter... "
-    walter -v | grep -q 'Walter version'
-    echo "OK"
-    echo -n "Checking PHPUnit... "
-    phpunit -version | grep -q 'PHPUnit'
-    echo "OK"
-    echo -n "Checking SSH client... "
-    ssh -V &>/dev/null
-    echo "OK"
-}
+echo -n "Checking composer... "
+composer --version | grep -q 'Composer version'
+echo "OK"
 
-checkPhpModules
-checkTools
+echo -n "Checking walter... "
+walter -v | grep -q 'Walter version'
+echo "OK"
+
+echo -n "Checking PHPUnit... "
+phpunit -version | grep -q 'PHPUnit'
+echo "OK"
+
+echo -n "Checking SSH client... "
+ssh -V | grep -q 'OpenSSH'
+echo "OK"
